# Generated by Django 5.0.6 on 2024-06-21 21:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcionProducto',
            field=models.CharField(default=django.utils.timezone.now, max_length=300, verbose_name='Descripción del Producto'),
            preserve_default=False,
        ),
    ]
