# Generated by Django 5.0.6 on 2024-06-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_producto_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escultura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('fecha_fabricacion', models.DateField()),
                ('imagen', models.ImageField(null=True, upload_to='Escultura')),
            ],
        ),
        migrations.CreateModel(
            name='Pintura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('fecha_fabricacion', models.DateField()),
                ('imagen', models.ImageField(null=True, upload_to='Pintura')),
            ],
        ),
    ]
